repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.10.0
  hooks:
  - id: commitizen
    stages: [commit-msg]

- repo: local
  hooks:
  - id: pytest
    name: pytest
    language: system
    entry: make test
    always_run: true
    pass_filenames: false
    verbose: true
    stages: [commit]
