[project]
name = "j-auth-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
]

[dependency-groups]
test = [
    "pytest>=8.3.4",
    "ruff>=0.8.4",
]


[tool.ruff.lint]
select = ["I"]
